import { Injectable } from '@angular/core';

export type RolverseLang = 'es' | 'en';

@Injectable({
  providedIn: 'root',
})
export class TranslateService {
  currentLang: RolverseLang = 'es';

  private readonly storageKey = 'rolverse_lang';

  private readonly translations: Record<RolverseLang, Record<string, string>> = {
    es: {
      'HEADER.LOGIN': 'Iniciar Sesión',
      'HEADER.LOGOUT': 'Cerrar Sesión',
      'HEADER.MY_ACCOUNT': 'Mi cuenta',
      'HEADER.PROFILE': 'Mi perfil',
      'HEADER.NEWS': 'Noticias',
      'HEADER.FORUM': 'Foro',
      'HEADER.MATCHES': 'Partidas',
      'HEADER.CHARACTERS': 'Personajes',
      'HEADER.MAPS': 'Mapas',
      'HEADER.PLANETS': 'Planetas',
      'HEADER.GAME_SYSTEM': 'Sistema de Juego',
      'HEADER.HISTORY': 'Historia',
      'HEADER.STORIES': 'Historias',
      'HEADER.BESTIARY': 'Bestiario',
      'HEADER.LANGUAGE_ES': 'Cambiar idioma a español',
      'HEADER.LANGUAGE_EN': 'Cambiar idioma a inglés',

      'AUTH.LOGIN_TITLE': 'Iniciar Sesión',
      'AUTH.EMAIL': 'Email',
      'AUTH.PASSWORD': 'Contraseña',
      'AUTH.LOGIN_BUTTON': 'Iniciar Sesión',
      'AUTH.NO_ACCOUNT': '¿No tienes cuenta? Regístrate',
      'AUTH.HAVE_ACCOUNT': '¿Tienes una cuenta? Inicia Sesión',
      'AUTH.FORGOT_PASSWORD': '¿Olvidaste tu contraseña?',
      'AUTH.RECOVER_TITLE': 'Recuperar contraseña',
      'AUTH.SEND_NEW_PASSWORD': 'Enviar nueva contraseña',
      'AUTH.SENDING': 'Enviando...',
      'AUTH.BACK_HOME': 'Volver a la homepage',
      'AUTH.REGISTER_TITLE': 'Registro',
      'AUTH.NAME': 'Nombre',
      'AUTH.REGISTER_BUTTON': 'Registrarse',
      'AUTH.SHOW_PASSWORD': 'Ver',
      'AUTH.HIDE_PASSWORD': 'Ocultar',

      'COMMON.SAVE': 'Guardar',
      'COMMON.SAVING': 'Guardando...',
      'COMMON.CANCEL': 'Cancelar',
      'COMMON.EDIT': 'Editar',
      'COMMON.DELETE': 'Eliminar',
      'COMMON.SEARCH': 'Buscar',
      'COMMON.ENTER': 'Entrar',
      'COMMON.NEXT': 'Siguiente',
      'COMMON.PREVIOUS': 'Anterior',
      'COMMON.PAGE': 'Página',
      'COMMON.OF': 'de',

      'HOME.TOP_1': 'Desde las mazmorras más oscuras hasta las galaxias más lejanas...',
      'HOME.TOP_2': 'D&D, Pathfinder, Anima, Star Wars, Cthulhu y más...',
      'HOME.TOP_3': '¡Descubre mundos, crea héroes, vive el rol!',
      'HOME.BOTTOM_1': 'Explora. Imagina. Juega.',
      'HOME.BOTTOM_2': 'Rolverse: el hogar de los aventureros modernos.',
      'HOME.CHARACTER_CREATOR': 'Creador de personajes',
      'HOME.GO_TO_MATCHES': 'Ir a Partidas',
      'HOME.LOADING_MATCHES': 'Cargando partidas...',
      'HOME.NO_MATCHES': 'Todavía no hay partidas disponibles.',
      'HOME.LOADING_FORUMS': 'Cargando foros...',
      'HOME.NO_FORUMS': 'Todavía no hay foros disponibles.',

      'NEWS.LATEST': 'Últimas noticias del Mundo de Rol',
      'NEWS.ADD': 'Agregar noticia',
      'NEWS.EDIT': 'Editar noticia',
      'NEWS.DELETE': 'Eliminar noticia',
      'NEWS.VIEW': 'Ver noticia',
      'NEWS.LOADING': 'Cargando noticias...',
      'NEWS.EDIT_TITLE': 'Editar noticia',
      'NEWS.ADD_TITLE': 'Agregar nueva noticia',
      'NEWS.TITLE_FIELD': 'Título',
      'NEWS.SUMMARY': 'Resumen',
      'NEWS.CREATED_AT': 'Fecha de creación',
      'NEWS.IMAGE': 'Imagen',
      'NEWS.DESCRIPTION': 'Descripción',
      'NEWS.SAVE': 'Guardar noticia',
      'NEWS.PUBLISH': 'Publicar noticia',
      'NEWS.BACK_TO_NEWS': 'Volver a Noticias',
      'NEWS.LOADING_DETAIL': 'Cargando noticia...',
      'NEWS.REVIEWS': 'Reseñas',
      'NEWS.REVIEW_PLACEHOLDER': 'Escribe tu reseña aquí...',
      'NEWS.ATTACH_IMAGE': 'Adjuntar imagen',
      'NEWS.PUBLISH_COMMENT': 'Publicar comentario',
      'NEWS.SELECTED_IMAGE': 'Imagen seleccionada',
      'NEWS.LOGIN_TO_COMMENT': 'Inicia sesión para comentar esta noticia.',
      'NEWS.EDIT_REVIEW_PLACEHOLDER': 'Edita tu reseña...',
      'NEWS.CHANGE_IMAGE': 'Cambiar imagen',
      'NEWS.CLOSE': 'Cerrar',

      'FORUM.KICKER': 'Tablón de Rolverse',
      'FORUM.TITLE': 'Concilio de Rol y Estrategia',
      'FORUM.SUBTITLE': 'Salas de debate, crónicas de partida y consejos de aventureros.',
      'FORUM.CREATE': 'Crear foro',
      'FORUM.EDIT': 'Editar foro',
      'FORUM.PUBLIC_ROOM': 'Sala pública',
      'FORUM.PRIVATE_ROOM': 'Sala privada',
      'FORUM.EMPTY_TITLE': 'No hay salas abiertas',
      'FORUM.EMPTY_TEXT': 'El tablón está preparado para la primera convocatoria.',
      'FORUM.TYPE': 'Tipo',
      'FORUM.ACCESS': 'Acceso',
      'FORUM.DESCRIPTION': 'Descripción',
      'FORUM.ROOM_TYPE': 'Tipo de sala',
      'FORUM.CREATE_TITLE': 'Crear nuevo foro',
      'FORUM.TITLE_PLACEHOLDER': 'Título del foro',
      'FORUM.DESCRIPTION_PLACEHOLDER': 'Descripción del foro',
      'FORUM.TITLE_REQUIRED': 'El título es obligatorio',
      'FORUM.DESCRIPTION_REQUIRED': 'La descripción es obligatoria',
      'FORUM.SELECT_ROOM_TYPE': 'Selecciona el tipo de sala',
      'FORUM.COUNCIL_ROOM': 'Sala del concilio',
      'FORUM.BACK_TO_BOARD': 'Volver al tablón',
      'FORUM.PRIVACY_TEXT': 'Gestiona si este foro es visible para todos o solo para miembros invitados.',
      'FORUM.INVITE_PRIVATE_ROOM': 'Invitar a sala privada',
      'FORUM.INVITE_HELP': 'Busca usuarios registrados por email y envía una invitación.',
      'FORUM.SEARCH_USER_EMAIL': 'Buscar usuario por email',
      'FORUM.INVITE': 'Invitar',
      'FORUM.MESSAGES_TITLE': 'Mensajes del Concilio',
      'FORUM.MESSAGES': 'mensajes',
      'FORUM.FORUM_MEMBER': 'Miembro del foro',
      'FORUM.PUBLISHED': 'Publicado',
      'FORUM.MESSAGE': 'Mensaje',
      'FORUM.CURRENT_IMAGE': 'Imagen actual',
      'FORUM.NEW_IMAGE': 'Nueva imagen',
      'FORUM.CHANGE_IMAGE': 'Cambiar imagen',
      'FORUM.NO_MESSAGES_TITLE': 'Ningún aventurero ha hablado aún',
      'FORUM.NO_MESSAGES_TEXT': 'Abre la conversación con el primer mensaje de la sala.',
      'FORUM.REPLY_TITLE': 'Responder al concilio',
      'FORUM.MESSAGE_PLACEHOLDER': 'Escribe tu mensaje como un aventurero...',
      'FORUM.ATTACH_IMAGE': 'Adjuntar imagen',
      'FORUM.SEND_MESSAGE': 'Enviar mensaje',
      'FORUM.SELECTED_IMAGE': 'Imagen seleccionada',
      'FORUM.LOGIN_TO_COMMENT': 'Inicia sesión para comentar en el foro.',
      'FORUM.NOT_FOUND_TITLE': 'El foro ha desaparecido entre las brumas',
      'FORUM.NOT_FOUND_TEXT': 'Puede que el concilio haya sido disuelto.',

      'MATCHES.KICKER': 'Mesa de aventuras',
      'MATCHES.TITLE': 'Partidas de Rolverse',
      'MATCHES.SUBTITLE': 'Campañas activas y crónicas finalizadas para explorar o jugar.',
      'MATCHES.CREATE': 'Crear partida',
      'MATCHES.CREATING': 'Creando...',
      'MATCHES.EDIT': 'Editar partida',
      'MATCHES.DELETE': 'Eliminar partida',
      'MATCHES.VIEW': 'Ver partida',
      'MATCHES.FINISH': 'Finalizar partida',
      'MATCHES.SEARCH_PLACEHOLDER': 'Buscar por título',
      'MATCHES.LOADING': 'Cargando partidas...',
      'MATCHES.EMPTY': 'Todavía no hay partidas disponibles.',
      'MATCHES.ACTIVE': 'En juego',
      'MATCHES.FINISHED': 'Finalizada',
      'MATCHES.PUBLIC': 'Pública',
      'MATCHES.PRIVATE': 'Privada',
      'MATCHES.TITLE_FIELD': 'Título',
      'MATCHES.SHORT_DESCRIPTION': 'Descripción corta',
      'MATCHES.SYSTEM_NAME': 'Sistema de juego',
      'MATCHES.ACCESS_TYPE': 'Tipo de acceso',
      'MATCHES.PUBLIC_MATCH': 'Partida pública',
      'MATCHES.PRIVATE_MATCH': 'Partida privada',
      'MATCHES.FULL_DESCRIPTION': 'Historia / descripción completa',
      'MATCHES.RULES': 'Reglas',
      'MATCHES.COVER': 'Portada',
      'MATCHES.CHARACTERS': 'Personajes',
      'MATCHES.MODULES': 'Anexos',
      'MATCHES.BOARDS': 'Tableros',
      'MATCHES.COMBAT': 'Combates',
      'MATCHES.ACTIONS': 'Acciones',
      'MATCHES.ROLL_DICE': 'Tirar dados',
      'MATCHES.CHANGE_COVER': 'Cambiar portada',
      'MATCHES.SAVE_CHANGES': 'Guardar cambios',
      'MATCHES.BACK_TO_MATCHES': 'Volver a Partidas',
      'MATCHES.ROLEPLAY_MATCH': 'Partida de rol',
      'MATCHES.SYSTEM': 'Sistema',
      'MATCHES.DIRECTOR': 'Director',
      'MATCHES.ACCESS_SETTINGS_TITLE': 'Tipo de partida',
      'MATCHES.ACCESS_SETTINGS_TEXT': 'Gestiona si esta partida es visible para todos o solo para jugadores invitados.',
      'MATCHES.SHOW_DETAILS': 'Saber más',
      'MATCHES.HIDE_DETAILS': 'Ocultar detalles',
      'MATCHES.ENTER_MATCH': 'Entrar a la partida',
      'MATCHES.JOIN_MATCH': 'Unirse a la partida',
      'MATCHES.JOINING': 'Uniendo...',
      'MATCHES.STORY': 'Historia',
      'MATCHES.NO_STORY': 'Sin historia detallada.',
      'MATCHES.NO_RULES': 'Sin reglas adicionales.',
      'MATCHES.SCENE': 'Escena de partida',
      'MATCHES.FINISHED_NOTICE': 'Partida finalizada.',
      'MATCHES.CLOSE_EDIT': 'Cerrar edición',
      'MATCHES.INVITE_USERS': 'Invitar usuarios',
      'MATCHES.INVITE_PLACEHOLDER': 'Buscar usuario por email',
      'MATCHES.INVITE': 'Invitar',
      'MATCHES.CREATE_CHARACTER': 'Crear o editar mi personaje',
      'MATCHES.DESCRIPTION': 'Descripción',
      'MATCHES.CHARACTER_IMAGE': 'Imagen del personaje',
      'MATCHES.SAVE_CHARACTER': 'Guardar personaje',
      'MATCHES.UPLOAD_MODULE': 'Subir módulo o manual',
      'MATCHES.FILE': 'Archivo',
      'MATCHES.DOWNLOAD': 'Descargar',
      'MATCHES.UPLOAD_BOARD': 'Subir tablero o mapa',
      'MATCHES.IMAGE': 'Imagen',
      'MATCHES.CHAT': 'Chat de partida',
      'MATCHES.MESSAGE_PLACEHOLDER': 'Escribe en la escena',
      'MATCHES.ATTACH_IMAGE': 'Adjuntar imagen',
      'MATCHES.SEND': 'Enviar',
      'MATCHES.ACTION_PLACEHOLDER': 'Describe tu acción',
      'MATCHES.ROLL_WITH_ACTION': 'Tirar dados con la acción',
      'MATCHES.SEND_ACTION': 'Enviar acción',
      'MATCHES.DICE': 'Dados',
      'MATCHES.TOTAL': 'Total',
      'MATCHES.MASTER_RESPONSE': 'Respuesta del master',
      'MATCHES.APPROVE': 'Aprobar',
      'MATCHES.REJECT': 'Rechazar',
      'MATCHES.USER': 'Usuario',

      'PROFILE.LOADING': 'Cargando perfil...',
      'PROFILE.UPLOADING': 'Subiendo...',
      'PROFILE.CHANGE_PHOTO': 'Cambiar foto',
      'PROFILE.EMAIL': 'Email',
      'PROFILE.ROLE': 'Rol',
      'PROFILE.MESSAGE_COUNT': 'Mensajes enviados',
      'PROFILE.CHARISMA': 'Carisma',
      'PROFILE.FRIKIPOINTS': 'Frikipuntos',
      'PROFILE.GAME_MASTER': 'Director de juego',
      'PROFILE.YES': 'Sí',
      'PROFILE.NO': 'No',
      'PROFILE.LAST_LOGIN': 'Último acceso',
      'PROFILE.NEVER': 'Nunca',
      'PROFILE.CREATED_AT': 'Fecha de registro',
      'PROFILE.CHANGE_PASSWORD': 'Cambiar contraseña',
      'PROFILE.CURRENT_PASSWORD': 'Contraseña actual',
      'PROFILE.NEW_PASSWORD': 'Nueva contraseña',
      'PROFILE.CONFIRM_PASSWORD': 'Confirmar nueva contraseña',
      'PROFILE.SAVE_PASSWORD': 'Guardar nueva contraseña',
      'PROFILE.MY_FORUMS': 'Mis Foros',
      'PROFILE.MY_NEWS': 'Mis Noticias',
      'PROFILE.MY_MATCHES': 'Mis Partidas',
      'PROFILE.NO_FORUMS': 'Todavía no has creado foros.',
      'PROFILE.NO_NEWS': 'Todavía no has creado noticias.',
      'PROFILE.DIRECTOR_ACTIVE': 'Director en juego',
      'PROFILE.PLAYER_ACTIVE': 'Jugador en juego',
      'PROFILE.DIRECTOR_FINISHED': 'Director finalizadas',
      'PROFILE.PLAYER_FINISHED': 'Jugador finalizadas',
      'PROFILE.TOTAL_MATCHES': 'Total partidas',
      'PROFILE.DIRECTOR_ACTIVE_MATCHES': 'Partidas como director en juego',
      'PROFILE.PLAYER_ACTIVE_MATCHES': 'Partidas como jugador en juego',
      'PROFILE.DIRECTOR_FINISHED_MATCHES': 'Partidas como director finalizadas',
      'PROFILE.PLAYER_FINISHED_MATCHES': 'Partidas como jugador finalizadas',
      'PROFILE.NO_DIRECTOR_ACTIVE': 'No tienes partidas activas como director.',
      'PROFILE.NO_PLAYER_ACTIVE': 'No tienes partidas activas como jugador.',
      'PROFILE.NO_DIRECTOR_FINISHED': 'No tienes partidas finalizadas como director.',
      'PROFILE.NO_PLAYER_FINISHED': 'No tienes partidas finalizadas como jugador.',
      'PROFILE.FORUM_INVITATIONS': 'Invitaciones a foros privados',
      'PROFILE.MATCH_INVITATIONS': 'Invitaciones a partidas',
      'PROFILE.INVITATION_FROM': 'Invitación de',
      'PROFILE.ACCEPT': 'Aceptar',
      'PROFILE.REJECT': 'Rechazar',
      'PROFILE.NO_INVITATIONS': 'No tienes invitaciones pendientes.',
      'PROFILE.NO_MATCH_INVITATIONS': 'No tienes invitaciones de partidas pendientes.',

      'FOOTER.ABOUT': 'Acerca de',
      'FOOTER.CONTACT': 'Contacto',
      'FOOTER.RIGHTS': '© 2025 Rolverse. Todos los derechos reservados.',
    },
    en: {
      'HEADER.LOGIN': 'Log In',
      'HEADER.LOGOUT': 'Log Out',
      'HEADER.MY_ACCOUNT': 'My Account',
      'HEADER.PROFILE': 'My profile',
      'HEADER.NEWS': 'News',
      'HEADER.FORUM': 'Forum',
      'HEADER.MATCHES': 'Matches',
      'HEADER.CHARACTERS': 'Characters',
      'HEADER.MAPS': 'Maps',
      'HEADER.PLANETS': 'Planets',
      'HEADER.GAME_SYSTEM': 'Game System',
      'HEADER.HISTORY': 'History',
      'HEADER.STORIES': 'Stories',
      'HEADER.BESTIARY': 'Bestiary',
      'HEADER.LANGUAGE_ES': 'Switch language to Spanish',
      'HEADER.LANGUAGE_EN': 'Switch language to English',

      'AUTH.LOGIN_TITLE': 'Log In',
      'AUTH.EMAIL': 'Email',
      'AUTH.PASSWORD': 'Password',
      'AUTH.LOGIN_BUTTON': 'Log In',
      'AUTH.NO_ACCOUNT': 'No account? Register',
      'AUTH.HAVE_ACCOUNT': 'Already have an account? Log In',
      'AUTH.FORGOT_PASSWORD': 'Forgot your password?',
      'AUTH.RECOVER_TITLE': 'Recover password',
      'AUTH.SEND_NEW_PASSWORD': 'Send new password',
      'AUTH.SENDING': 'Sending...',
      'AUTH.BACK_HOME': 'Back to homepage',
      'AUTH.REGISTER_TITLE': 'Register',
      'AUTH.NAME': 'Name',
      'AUTH.REGISTER_BUTTON': 'Register',
      'AUTH.SHOW_PASSWORD': 'Show',
      'AUTH.HIDE_PASSWORD': 'Hide',

      'COMMON.SAVE': 'Save',
      'COMMON.SAVING': 'Saving...',
      'COMMON.CANCEL': 'Cancel',
      'COMMON.EDIT': 'Edit',
      'COMMON.DELETE': 'Delete',
      'COMMON.SEARCH': 'Search',
      'COMMON.ENTER': 'Enter',
      'COMMON.NEXT': 'Next',
      'COMMON.PREVIOUS': 'Previous',
      'COMMON.PAGE': 'Page',
      'COMMON.OF': 'of',

      'HOME.TOP_1': 'From the darkest dungeons to the farthest galaxies...',
      'HOME.TOP_2': 'D&D, Pathfinder, Anima, Star Wars, Cthulhu and more...',
      'HOME.TOP_3': 'Discover worlds, create heroes, live roleplay!',
      'HOME.BOTTOM_1': 'Explore. Imagine. Play.',
      'HOME.BOTTOM_2': 'Rolverse: home of modern adventurers.',
      'HOME.CHARACTER_CREATOR': 'Character creator',
      'HOME.GO_TO_MATCHES': 'Go to Matches',
      'HOME.LOADING_MATCHES': 'Loading matches...',
      'HOME.NO_MATCHES': 'No matches available yet.',
      'HOME.LOADING_FORUMS': 'Loading forums...',
      'HOME.NO_FORUMS': 'No forums available yet.',

      'NEWS.LATEST': 'Latest Roleplaying News',
      'NEWS.ADD': 'Add news',
      'NEWS.EDIT': 'Edit news',
      'NEWS.DELETE': 'Delete news',
      'NEWS.VIEW': 'View news',
      'NEWS.LOADING': 'Loading news...',
      'NEWS.EDIT_TITLE': 'Edit news',
      'NEWS.ADD_TITLE': 'Add new news',
      'NEWS.TITLE_FIELD': 'Title',
      'NEWS.SUMMARY': 'Summary',
      'NEWS.CREATED_AT': 'Creation date',
      'NEWS.IMAGE': 'Image',
      'NEWS.DESCRIPTION': 'Description',
      'NEWS.SAVE': 'Save news',
      'NEWS.PUBLISH': 'Publish news',
      'NEWS.BACK_TO_NEWS': 'Back to News',
      'NEWS.LOADING_DETAIL': 'Loading news...',
      'NEWS.REVIEWS': 'Reviews',
      'NEWS.REVIEW_PLACEHOLDER': 'Write your review here...',
      'NEWS.ATTACH_IMAGE': 'Attach image',
      'NEWS.PUBLISH_COMMENT': 'Publish comment',
      'NEWS.SELECTED_IMAGE': 'Selected image',
      'NEWS.LOGIN_TO_COMMENT': 'Log in to comment on this news.',
      'NEWS.EDIT_REVIEW_PLACEHOLDER': 'Edit your review...',
      'NEWS.CHANGE_IMAGE': 'Change image',
      'NEWS.CLOSE': 'Close',

      'FORUM.KICKER': 'Rolverse Board',
      'FORUM.TITLE': 'Council of Roleplay and Strategy',
      'FORUM.SUBTITLE': 'Discussion rooms, campaign chronicles and adventurer advice.',
      'FORUM.CREATE': 'Create forum',
      'FORUM.EDIT': 'Edit forum',
      'FORUM.PUBLIC_ROOM': 'Public room',
      'FORUM.PRIVATE_ROOM': 'Private room',
      'FORUM.EMPTY_TITLE': 'No open rooms',
      'FORUM.EMPTY_TEXT': 'The board is ready for the first call.',
      'FORUM.TYPE': 'Type',
      'FORUM.ACCESS': 'Access',
      'FORUM.DESCRIPTION': 'Description',
      'FORUM.ROOM_TYPE': 'Room type',
      'FORUM.CREATE_TITLE': 'Create new forum',
      'FORUM.TITLE_PLACEHOLDER': 'Forum title',
      'FORUM.DESCRIPTION_PLACEHOLDER': 'Forum description',
      'FORUM.TITLE_REQUIRED': 'Title is required',
      'FORUM.DESCRIPTION_REQUIRED': 'Description is required',
      'FORUM.SELECT_ROOM_TYPE': 'Select the room type',
      'FORUM.COUNCIL_ROOM': 'Council room',
      'FORUM.BACK_TO_BOARD': 'Back to board',
      'FORUM.PRIVACY_TEXT': 'Manage whether this forum is visible to everyone or only invited members.',
      'FORUM.INVITE_PRIVATE_ROOM': 'Invite to private room',
      'FORUM.INVITE_HELP': 'Search registered users by email and send an invitation.',
      'FORUM.SEARCH_USER_EMAIL': 'Search user by email',
      'FORUM.INVITE': 'Invite',
      'FORUM.MESSAGES_TITLE': 'Council Messages',
      'FORUM.MESSAGES': 'messages',
      'FORUM.FORUM_MEMBER': 'Forum member',
      'FORUM.PUBLISHED': 'Published',
      'FORUM.MESSAGE': 'Message',
      'FORUM.CURRENT_IMAGE': 'Current image',
      'FORUM.NEW_IMAGE': 'New image',
      'FORUM.CHANGE_IMAGE': 'Change image',
      'FORUM.NO_MESSAGES_TITLE': 'No adventurer has spoken yet',
      'FORUM.NO_MESSAGES_TEXT': 'Open the conversation with the first room message.',
      'FORUM.REPLY_TITLE': 'Reply to the council',
      'FORUM.MESSAGE_PLACEHOLDER': 'Write your message like an adventurer...',
      'FORUM.ATTACH_IMAGE': 'Attach image',
      'FORUM.SEND_MESSAGE': 'Send message',
      'FORUM.SELECTED_IMAGE': 'Selected image',
      'FORUM.LOGIN_TO_COMMENT': 'Log in to comment in the forum.',
      'FORUM.NOT_FOUND_TITLE': 'The forum has vanished into the mists',
      'FORUM.NOT_FOUND_TEXT': 'The council may have been dissolved.',

      'MATCHES.KICKER': 'Adventure table',
      'MATCHES.TITLE': 'Rolverse Matches',
      'MATCHES.SUBTITLE': 'Active campaigns and finished chronicles to explore or play.',
      'MATCHES.CREATE': 'Create match',
      'MATCHES.CREATING': 'Creating...',
      'MATCHES.EDIT': 'Edit match',
      'MATCHES.DELETE': 'Delete match',
      'MATCHES.VIEW': 'View match',
      'MATCHES.FINISH': 'Finish match',
      'MATCHES.SEARCH_PLACEHOLDER': 'Search by title',
      'MATCHES.LOADING': 'Loading matches...',
      'MATCHES.EMPTY': 'No matches available yet.',
      'MATCHES.ACTIVE': 'Active',
      'MATCHES.FINISHED': 'Finished',
      'MATCHES.PUBLIC': 'Public',
      'MATCHES.PRIVATE': 'Private',
      'MATCHES.TITLE_FIELD': 'Title',
      'MATCHES.SHORT_DESCRIPTION': 'Short description',
      'MATCHES.SYSTEM_NAME': 'Game system',
      'MATCHES.ACCESS_TYPE': 'Access type',
      'MATCHES.PUBLIC_MATCH': 'Public match',
      'MATCHES.PRIVATE_MATCH': 'Private match',
      'MATCHES.FULL_DESCRIPTION': 'Story / full description',
      'MATCHES.RULES': 'Rules',
      'MATCHES.COVER': 'Cover',
      'MATCHES.CHARACTERS': 'Characters',
      'MATCHES.MODULES': 'Annexes',
      'MATCHES.BOARDS': 'Boards',
      'MATCHES.COMBAT': 'Combat',
      'MATCHES.ACTIONS': 'Actions',
      'MATCHES.ROLL_DICE': 'Roll dice',
      'MATCHES.CHANGE_COVER': 'Change cover',
      'MATCHES.SAVE_CHANGES': 'Save changes',
      'MATCHES.BACK_TO_MATCHES': 'Back to Matches',
      'MATCHES.ROLEPLAY_MATCH': 'Roleplaying match',
      'MATCHES.SYSTEM': 'System',
      'MATCHES.DIRECTOR': 'Director',
      'MATCHES.ACCESS_SETTINGS_TITLE': 'Match type',
      'MATCHES.ACCESS_SETTINGS_TEXT': 'Manage whether this match is visible to everyone or only invited players.',
      'MATCHES.SHOW_DETAILS': 'Learn more',
      'MATCHES.HIDE_DETAILS': 'Hide details',
      'MATCHES.ENTER_MATCH': 'Enter match',
      'MATCHES.JOIN_MATCH': 'Join match',
      'MATCHES.JOINING': 'Joining...',
      'MATCHES.STORY': 'Story',
      'MATCHES.NO_STORY': 'No detailed story.',
      'MATCHES.NO_RULES': 'No additional rules.',
      'MATCHES.SCENE': 'Match scene',
      'MATCHES.FINISHED_NOTICE': 'Match finished.',
      'MATCHES.CLOSE_EDIT': 'Close edit',
      'MATCHES.INVITE_USERS': 'Invite users',
      'MATCHES.INVITE_PLACEHOLDER': 'Search user by email',
      'MATCHES.INVITE': 'Invite',
      'MATCHES.CREATE_CHARACTER': 'Create or edit my character',
      'MATCHES.DESCRIPTION': 'Description',
      'MATCHES.CHARACTER_IMAGE': 'Character image',
      'MATCHES.SAVE_CHARACTER': 'Save character',
      'MATCHES.UPLOAD_MODULE': 'Upload module or manual',
      'MATCHES.FILE': 'File',
      'MATCHES.DOWNLOAD': 'Download',
      'MATCHES.UPLOAD_BOARD': 'Upload board or map',
      'MATCHES.IMAGE': 'Image',
      'MATCHES.CHAT': 'Match chat',
      'MATCHES.MESSAGE_PLACEHOLDER': 'Write in the scene',
      'MATCHES.ATTACH_IMAGE': 'Attach image',
      'MATCHES.SEND': 'Send',
      'MATCHES.ACTION_PLACEHOLDER': 'Describe your action',
      'MATCHES.ROLL_WITH_ACTION': 'Roll dice with the action',
      'MATCHES.SEND_ACTION': 'Send action',
      'MATCHES.DICE': 'Dice',
      'MATCHES.TOTAL': 'Total',
      'MATCHES.MASTER_RESPONSE': 'Master response',
      'MATCHES.APPROVE': 'Approve',
      'MATCHES.REJECT': 'Reject',
      'MATCHES.USER': 'User',

      'PROFILE.LOADING': 'Loading profile...',
      'PROFILE.UPLOADING': 'Uploading...',
      'PROFILE.CHANGE_PHOTO': 'Change photo',
      'PROFILE.EMAIL': 'Email',
      'PROFILE.ROLE': 'Role',
      'PROFILE.MESSAGE_COUNT': 'Messages sent',
      'PROFILE.CHARISMA': 'Charisma',
      'PROFILE.FRIKIPOINTS': 'Frikipoints',
      'PROFILE.GAME_MASTER': 'Game master',
      'PROFILE.YES': 'Yes',
      'PROFILE.NO': 'No',
      'PROFILE.LAST_LOGIN': 'Last login',
      'PROFILE.NEVER': 'Never',
      'PROFILE.CREATED_AT': 'Registration date',
      'PROFILE.CHANGE_PASSWORD': 'Change password',
      'PROFILE.CURRENT_PASSWORD': 'Current password',
      'PROFILE.NEW_PASSWORD': 'New password',
      'PROFILE.CONFIRM_PASSWORD': 'Confirm new password',
      'PROFILE.SAVE_PASSWORD': 'Save new password',
      'PROFILE.MY_FORUMS': 'My Forums',
      'PROFILE.MY_NEWS': 'My News',
      'PROFILE.MY_MATCHES': 'My Matches',
      'PROFILE.NO_FORUMS': 'You have not created forums yet.',
      'PROFILE.NO_NEWS': 'You have not created news yet.',
      'PROFILE.DIRECTOR_ACTIVE': 'Director active',
      'PROFILE.PLAYER_ACTIVE': 'Player active',
      'PROFILE.DIRECTOR_FINISHED': 'Director finished',
      'PROFILE.PLAYER_FINISHED': 'Player finished',
      'PROFILE.TOTAL_MATCHES': 'Total matches',
      'PROFILE.DIRECTOR_ACTIVE_MATCHES': 'Matches as active director',
      'PROFILE.PLAYER_ACTIVE_MATCHES': 'Matches as active player',
      'PROFILE.DIRECTOR_FINISHED_MATCHES': 'Matches as finished director',
      'PROFILE.PLAYER_FINISHED_MATCHES': 'Matches as finished player',
      'PROFILE.NO_DIRECTOR_ACTIVE': 'You have no active matches as director.',
      'PROFILE.NO_PLAYER_ACTIVE': 'You have no active matches as player.',
      'PROFILE.NO_DIRECTOR_FINISHED': 'You have no finished matches as director.',
      'PROFILE.NO_PLAYER_FINISHED': 'You have no finished matches as player.',
      'PROFILE.FORUM_INVITATIONS': 'Private forum invitations',
      'PROFILE.MATCH_INVITATIONS': 'Match invitations',
      'PROFILE.INVITATION_FROM': 'Invitation from',
      'PROFILE.ACCEPT': 'Accept',
      'PROFILE.REJECT': 'Reject',
      'PROFILE.NO_INVITATIONS': 'You have no pending invitations.',
      'PROFILE.NO_MATCH_INVITATIONS': 'You have no pending match invitations.',

      'FOOTER.ABOUT': 'About',
      'FOOTER.CONTACT': 'Contact',
      'FOOTER.RIGHTS': '© 2025 Rolverse. All rights reserved.',
    },
  };

  constructor() {
    const savedLang = localStorage.getItem(this.storageKey);
    if (savedLang === 'es' || savedLang === 'en') {
      this.currentLang = savedLang;
    }
  }

  setLanguage(lang: RolverseLang): void {
    this.currentLang = lang;
    localStorage.setItem(this.storageKey, lang);
  }

  translate(key: string): string {
    return this.translations[this.currentLang]?.[key] || key;
  }
}
